# repos:
# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.12.0
#   hooks:
#   - id: markdownlint
#     name: Markdownlint
#     description: Run markdownlint on your Markdown files
#     entry: mdl
#     language: ruby
#     files: \.(md|mdown|markdown)$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
